#!/usr/bin/python
# coding=utf-8

'''
Created on Mar 19, 2014

@author: Allis Tauri <allista@gmail.com>
'''

import os
from collections import Iterable
from PBSUtils.PBSJob import BatchFileJob, SerialJob, job_main

class DegenPrimerJob(SerialJob, BatchFileJob):
    
    _bin         = '/usr/local/bin/degen_primer'
    _name        = 'degen_primer_run'
    _description = 'Launch DegenPrimer as a serial job on a cluster. \
                    Accepts several .cfg files.'
    _extension   = '.cfg'
    
    def _new_job(self, conf_file):
        #get names of fasta nd seq_db files
        files = []
        for line in open(conf_file, 'r'):
            if not line: continue
            words  = line.split('=')
            if len(words) < 2: continue
            option = words[0].strip()
            value  = words[1].strip()
            if not value: continue
            if option == 'fasta_files':
                try: _files = eval(value)
                except: _files = None
                if not isinstance(_files, Iterable):
                    print 'Malformed fasta_files value: %s' % value
                    return None
                files.extend(_files)
            elif option == 'sequence_db':
                files.append(value)
        for stagein_file in files:
            if not os.path.isfile(stagein_file):
                print 'No such file: %s' % stagein_file
                return None
        #create job file
        job_file = self._jf.create_job([self._bin+' %(file1)s'],
                                       name=conf_file.rstrip(self._extension),
                                       walltime=self._walltime,
                                       stagein_files=[conf_file]+files)
        return job_file
    #end def
#end class

if __name__ == '__main__':
    job_main(DegenPrimerJob())