#!/usr/bin/python
# coding=utf-8

'''
Created on Dec 3, 2013

@author: Allis Tauri <allista@gmail.com>
'''

from PBSUtils.PBSJob import BatchFileJob, SerialJob, job_main

class MrBayesJob(SerialJob, BatchFileJob):
    
    _bin         = '/usr/lib/mrbayes-mpi/mb-mpi'
    _name        = 'mb_run'
    _description = 'Launch MrBayes as a serial job on a cluster. \
                    Accepts several .nex files.'
    _extension   = '.nex'
                    
    def _new_job(self, nex_file):
        return self._jf.create_job(['NP=$(cat /proc/cpuinfo | grep processor | wc -l)',
                                    '$(which mpirun) -np $NP %s %%(file1)s' % self._bin],
                                   name=nex_file.rstrip(self._extension),
                                   walltime=self._walltime,
                                   stagein_files=[nex_file])
    #end def
#end class

if __name__ == '__main__':
    job_main(MrBayesJob())